import { initializeApp, cert } from "firebase-admin/app";
import { getFirestore, Timestamp } from "firebase-admin/firestore";
import { readFileSync } from "fs";

// Load service account
const serviceAccount = JSON.parse(readFileSync("./scripts/serviceAccount.json", "utf8"));
initializeApp({ credential: cert(serviceAccount) });
const db = getFirestore();

const ENGAGEMENTS = [
  {
    customer: "Amazon EMA1",
    csId: "CS-16412", jiraKey: "CSE-1700",
    jiraLink: "https://safetyculture.atlassian.net/browse/CSE-1700",
    sfOppId: "006Mo00000Q4LgPIAV",
    sfOppLink: "https://safetyculture.lightning.force.com/lightning/r/Opportunity/006Mo00000Q4LgPIAV/view",
    csrLink: "https://safetyculture.lightning.force.com/lightning/r/CSM_Requests__c/a1BOl0000058n8jMAA/view",
    region: "EMEA", segment: "Strategic", subscription: "Premium",
    currentStage: "requirements", ragStatus: "green", planType: "Roadmap",
    oppType: "New Business", tshirt: "Standard", currency: "GBP £", arr: "",
    cseAssigneeName: "Ben Edwards", csmName: "Anna Hatfield-Shaw",
    integrations: [],
    notes: "Automate link between Amazon Work Order System (APM) and SC 1-min risk assessments (OMRA). Customer wants auto-population of OMRA template with Work Order number, equipment details and task description from APM.",
    lastJiraStatus: "Unplanned",
  },
  {
    customer: "Altrad",
    csId: "CS-16037", jiraKey: "CSE-1544",
    jiraLink: "https://safetyculture.atlassian.net/browse/CSE-1544",
    sfOppId: "006Mo00000WpkBFIAZ",
    sfOppLink: "https://safetyculture.lightning.force.com/lightning/r/Opportunity/006Mo00000WpkBFIAZ/view",
    csrLink: "https://safetyculture.lightning.force.com/lightning/r/CSM_Requests__c/a1BOl000004ceuzMAA/view",
    region: "EMEA", segment: "Enterprise", subscription: "Enterprise",
    currentStage: "technical-review", ragStatus: "amber", planType: "Roadmap",
    oppType: "New Business", tshirt: "Standard", currency: "GBP £", arr: "",
    cseAssigneeName: "Ben Edwards", csmName: "Chedz Mazarire",
    integrations: ["REST API"],
    notes: "Integrate with work order system iPlan. Customer wants SC to generate Pre-Job Brief with iPlan Work Order and Operation numbers pre-populated. 60,000 live work orders — GRS approach rejected, exploring API-based dynamic filtering.",
    lastJiraStatus: "Waiting on customer",
  },
  {
    customer: "DSV",
    csId: "CS-16411", jiraKey: "CSE-1699",
    jiraLink: "https://safetyculture.atlassian.net/browse/CSE-1699",
    sfOppId: "006Mo00000MSZO1IAP",
    sfOppLink: "https://safetyculture.lightning.force.com/lightning/r/Opportunity/006Mo00000MSZO1IAP/view",
    csrLink: "https://safetyculture.lightning.force.com/lightning/r/CSM_Requests__c/a1BOl0000058mUPMAY/view",
    region: "EMEA", segment: "Strategic", subscription: "Premium",
    currentStage: "requirements", ragStatus: "green", planType: "Roadmap",
    oppType: "New Business", tshirt: "Standard", currency: "GBP £", arr: "",
    cseAssigneeName: "Léo Furlan", csmName: "Jake Cooper-Woolley",
    integrations: [],
    notes: "Scope integration requirements — discovery call to be scheduled.",
    lastJiraStatus: "Waiting on customer",
  },
  {
    customer: "E.ON GFS (Green Funding Solutions)",
    csId: "CS-16346", jiraKey: "CSE-1679",
    jiraLink: "https://safetyculture.atlassian.net/browse/CSE-1679",
    sfOppId: "006Mo00000SX69mIAD",
    sfOppLink: "https://safetyculture.lightning.force.com/lightning/r/Opportunity/006Mo00000SX69mIAD/view",
    csrLink: "https://safetyculture.lightning.force.com/lightning/r/CSM_Requests__c/a1BOl0000052nUnMAI/view",
    region: "EMEA", segment: "Enterprise", subscription: "Enterprise",
    currentStage: "solution-delivery", ragStatus: "green", planType: "Roadmap",
    oppType: "New Business", tshirt: "Large", currency: "GBP £", arr: "",
    cseAssigneeName: "Jean-Francois Pypops", csmName: "Chedz Mazarire",
    integrations: ["Microsoft Fabric", "SharePoint"],
    modules: ["Inspections", "Actions"],
    notes: "External scaffolding contractors scan QR code → Microsoft Form (POC built by customer) → Power Automate → Workato → SC inspection auto-populated. E.ON GFS wants standardised digital handover cert for all external contractors UK-wide. Customer building POC. JF working with Jason Moore (HSSE Coordinator).",
    lastJiraStatus: "In Progress",
  },
  {
    customer: "Schneider Electric Solar",
    csId: "CS-16351", jiraKey: "CSE-1680",
    jiraLink: "https://safetyculture.atlassian.net/browse/CSE-1680",
    sfOppId: "006Ol00000PIYPrIAP",
    sfOppLink: "https://safetyculture.lightning.force.com/lightning/r/Opportunity/006Ol00000PIYPrIAP/view",
    csrLink: "https://safetyculture.lightning.force.com/lightning/r/CSM_Requests__c/a1BOl0000054CZBMA2/view",
    region: "EMEA", segment: "Strategic", subscription: "Premium",
    currentStage: "technical-review", ragStatus: "green", planType: "Roadmap",
    oppType: "New Business", tshirt: "Standard", currency: "GBP £", arr: "",
    cseAssigneeName: "Léo Furlan", csmName: "Youcef Hammoudi",
    integrations: ["REST API"],
    modules: ["Inspections"],
    notes: "Technical review of NetSuite/SC integration — inspection ownership, visibility, one-way data flow. SC recommended SetOwner endpoint post-record creation. Waiting on customer to confirm approach.",
    lastJiraStatus: "Waiting on customer",
  },
  {
    customer: "IKEA (Ingka Services AB)",
    csId: "CS-15284", jiraKey: "CSE-1143",
    jiraLink: "https://safetyculture.atlassian.net/browse/CSE-1143",
    sfOppId: "006Mo00000LHqvmIAD",
    sfOppLink: "https://safetyculture.lightning.force.com/lightning/r/Opportunity/006Mo00000LHqvmIAD/view",
    csrLink: "https://safetyculture.lightning.force.com/lightning/r/CSM_Requests__c/a1BMo000000wUqXMAU/view",
    region: "EMEA", segment: "Strategic", subscription: "Premium",
    currentStage: "onboarding", ragStatus: "amber", planType: "Onboarding",
    oppType: "Expansion", tshirt: "Large", currency: "USD $", arr: "1455070",
    cseAssigneeName: "Léo Furlan", csmName: "Emily Dellit",
    integrations: ["SSO", "SCIM"],
    modules: ["Inspections", "Schedules", "Actions", "Analytics"],
    notes: "IKEA Inter LUI project onboarding. Large strategic account. CSM: Kira Löffler. COM: Rebecca Critchley. Existing account ARR $1.45M.",
    lastJiraStatus: "Waiting on customer",
  },
  {
    customer: "Lux Airport",
    csId: "CS-16092", jiraKey: "CSE-1565",
    jiraLink: "https://safetyculture.atlassian.net/browse/CSE-1565",
    sfOppId: "006Mo00000OR8zlIAD",
    sfOppLink: "https://safetyculture.lightning.force.com/lightning/r/Opportunity/006Mo00000OR8zlIAD/view",
    csrLink: "https://safetyculture.lightning.force.com/lightning/r/CSM_Requests__c/a1BOl000004i90TMAQ/view",
    region: "EMEA", segment: "SB", subscription: "Premium",
    currentStage: "requirements", ragStatus: "green", planType: "Roadmap",
    oppType: "New Business", tshirt: "Standard", currency: "EUR €", arr: "",
    cseAssigneeName: "Léo Furlan", csmName: "Enzo Peluso",
    integrations: [],
    modules: ["Inspections", "Issues"],
    notes: "Integration between SC and Planon IWMS. Discovery call scheduled. JF to collect more information on what exactly they want to integrate (Inspections? Actions? Issues?) and contact at Planon.",
    lastJiraStatus: "In Progress",
  },
  {
    customer: "SSP UK",
    csId: "CS-16072", jiraKey: "CSE-1559",
    jiraLink: "https://safetyculture.atlassian.net/browse/CSE-1559",
    sfOppId: "006Mo00000PiVrKIAV",
    sfOppLink: "https://safetyculture.lightning.force.com/lightning/r/Opportunity/006Mo00000PiVrKIAV/view",
    csrLink: "https://safetyculture.lightning.force.com/lightning/r/CSM_Requests__c/a1BOl000004gRKsMAM/view",
    region: "EMEA", segment: "Strategic", subscription: "Premium",
    currentStage: "solution-delivery", ragStatus: "amber", planType: "Roadmap",
    oppType: "New Business", tshirt: "Standard", currency: "GBP £", arr: "",
    cseAssigneeName: "Léo Furlan", csmName: "Anna Hatfield-Shaw",
    integrations: ["Workato"],
    modules: ["Inspections"],
    notes: "Lock down inspections after completion via Workato recipe. Customer tested but mobile sync bug found when using Duplicate feature. Léo investigating. QSR industry — compliance is legal requirement.",
    lastJiraStatus: "Waiting on customer",
  },
  {
    customer: "Aspire Housing",
    csId: "CS-16073", jiraKey: "CSE-1560",
    jiraLink: "https://safetyculture.atlassian.net/browse/CSE-1560",
    sfOppId: "006Mo00000Tp7bRIAR",
    sfOppLink: "https://safetyculture.lightning.force.com/lightning/r/Opportunity/006Mo00000Tp7bRIAR/view",
    csrLink: "https://safetyculture.lightning.force.com/lightning/r/CSM_Requests__c/a1BOl000004gS2PMAU/view",
    region: "EMEA", segment: "Growth", subscription: "Premium",
    currentStage: "technical-review", ragStatus: "green", planType: "Roadmap",
    oppType: "New Business", tshirt: "Standard", currency: "GBP £", arr: "",
    cseAssigneeName: "Jean-Francois Pypops", csmName: "Mark Parut",
    integrations: ["Workato", "MS Excel"],
    modules: ["Inspections"],
    notes: "Two requirements: 1) Integrate SC with MRI Housing system — start new inspections automatically when new entry added (address matched to site). 2) Track Outlook email delivery via Excel log. Customer needs to confirm MRI Housing API access with vendor.",
    lastJiraStatus: "Waiting on customer",
  },
  {
    customer: "E.ON (EEISL)",
    csId: "CS-16152", jiraKey: "CSE-1597",
    jiraLink: "https://safetyculture.atlassian.net/browse/CSE-1597",
    sfOppId: "006Ol00000O9NXRIA3",
    sfOppLink: "https://safetyculture.lightning.force.com/lightning/r/Opportunity/006Ol00000O9NXRIA3/view",
    csrLink: "https://safetyculture.lightning.force.com/lightning/r/CSM_Requests__c/a1BOl000004mSvlMAE/view",
    region: "EMEA", segment: "Enterprise", subscription: "Premium",
    currentStage: "solution-delivery", ragStatus: "green", planType: "Roadmap",
    oppType: "New Business", tshirt: "Custom", currency: "GBP £", arr: "",
    cseAssigneeName: "Jean-Francois Pypops", csmName: "Filippo Pavone",
    integrations: ["REST API"],
    modules: ["Inspections", "Actions"],
    notes: "Complex enterprise SC webhooks → MuleSoft integration. Webhook authentication, sandbox environment setup, inspection/action data delivery. Token validity 180 days, auto-extended on use. Sandbox environment being enabled. JF working with E.ON integration team (Venkatesh, George, Rae Smith, Owen Lyttle).",
    lastJiraStatus: "In Progress",
  },
  {
    customer: "Cornerstone",
    csId: "CS-16158", jiraKey: "CSE-1601",
    jiraLink: "https://safetyculture.atlassian.net/browse/CSE-1601",
    sfOppId: "006Ol00000P739FIAR",
    sfOppLink: "https://safetyculture.lightning.force.com/lightning/r/Opportunity/006Ol00000P739FIAR/view",
    csrLink: "https://safetyculture.lightning.force.com/lightning/r/CSM_Requests__c/a1BOl000004msOnMAI/view",
    region: "EMEA", segment: "Growth", subscription: "Premium",
    currentStage: "go-live", ragStatus: "green", planType: "Roadmap",
    oppType: "New Business", tshirt: "Large", currency: "GBP £", arr: "",
    cseAssigneeName: "Jean-Francois Pypops", csmName: "Beth Francis",
    integrations: ["REST API"],
    modules: ["Inspections"],
    notes: "SC as field data capture layer — all inspection and media data integrates into Azure-based data platform (Fabric). All integration questions answered during onboarding meetings. Request closed.",
    lastJiraStatus: "Done",
  },
];

async function seed() {
  console.log(`Seeding ${ENGAGEMENTS.length} EMEA engagements...`);
  const now = Timestamp.now();
  
  for (const eng of ENGAGEMENTS) {
    const { cseAssigneeName, csmName, lastJiraStatus, ...data } = eng;
    const docRef = db.collection("engagements").doc();
    await docRef.set({
      ...data,
      aeUid: null, cseUid: null, csmUid: null, taUid: null,
      cseAssigneeName, csmName,
      stageTasks: {},
      stageCapture: {},
      createdBy: "seed-script",
      createdAt: now,
      updatedAt: now,
    });
    console.log(`  ✓ ${eng.customer} (${eng.csId}) → ${eng.currentStage}`);
  }
  
  console.log("\nDone! All EMEA engagements seeded.");
  process.exit(0);
}

seed().catch(err => { console.error(err); process.exit(1); });
